# Generated by Django 4.1.13 on 2025-07-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=32)),
                ('is_super', models.PositiveSmallIntegerField(default=0, verbose_name='是否超管')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('is_delete', models.PositiveSmallIntegerField(default=0, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myapp_admin_user',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='优惠券名称')),
                ('reduce_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='减免金额')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低消费金额')),
                ('total_num', models.PositiveIntegerField(default=0, verbose_name='发放数量')),
                ('receive_num', models.PositiveIntegerField(default=0, verbose_name='已领取数量')),
                ('expire_day', models.PositiveIntegerField(default=0, verbose_name='领取后有效期天数')),
                ('is_delete', models.PositiveSmallIntegerField(default=0, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myapp_coupon',
            },
        ),
        migrations.CreateModel(
            name='FreightTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('is_delete', models.PositiveSmallIntegerField(default=0, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myapp_freight_temp',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name='分类ID')),
                ('image_urls', models.JSONField(verbose_name='图片url列表')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('detail_url', models.CharField(max_length=255, verbose_name='详情图片url')),
                ('freight_type', models.SmallIntegerField(choices=[(1, '包邮'), (2, '固定邮费'), (3, '运费模板')], verbose_name='运费类型')),
                ('freight_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费金额，0元包邮')),
                ('freight_temp_id', models.IntegerField(default=0, verbose_name='运费模板ID')),
                ('is_delete', models.PositiveSmallIntegerField(default=0, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_goods_category',
            },
        ),
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(verbose_name='商品ID')),
                ('star_num', models.PositiveSmallIntegerField(default=5, verbose_name='评分')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'myapp_goods_comment',
            },
        ),
        migrations.CreateModel(
            name='GoodsSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(verbose_name='商品ID')),
                ('sku_name', models.CharField(max_length=255, verbose_name='SKU名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('line_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='划线价格')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myapp_goods_sku',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.SmallIntegerField(choices=[(1, 'Shop order'), (2, 'Points Shop order')], verbose_name='订单类型')),
                ('order_no', models.CharField(max_length=100, unique=True, verbose_name='订单号')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额（普通商城订单）')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='总积分（积分商城积分兑换订单）')),
                ('freight_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费金额')),
                ('coupon_id', models.IntegerField(default=0, verbose_name='优惠券ID（普通商城订单）')),
                ('coupon_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠券抵扣金额（普通商城订单）')),
                ('normal_points', models.PositiveIntegerField(default=0, verbose_name='用户输入普通积分数')),
                ('normal_points_deduct', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='普通积分抵扣金额（普通商城订单）')),
                ('normal_points_per_yuan', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='普通积分抵扣金额(1积分抵多少金额)单位：元')),
                ('cultural_points', models.PositiveIntegerField(default=0, verbose_name='用户输入文化积分数')),
                ('pay_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='付款金额（普通商城订单）')),
                ('give_normal_points', models.PositiveIntegerField(default=0, verbose_name='平台赠送普通积分（仅普通商城订单;确认收货后发）')),
                ('give_normal_points_granted', models.PositiveSmallIntegerField(default=0, verbose_name='平台赠送普通积分是否已发放')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('express_name', models.CharField(default='', max_length=255, verbose_name='快递公司名称')),
                ('express_no', models.CharField(default='', max_length=255, verbose_name='快递单号')),
                ('receipt_time', models.DateTimeField(blank=True, null=True, verbose_name='收货时间')),
                ('refund_coupon', models.PositiveSmallIntegerField(default=0, verbose_name='优惠券是否已退还（普通商城订单）')),
                ('refund_normal_points', models.PositiveIntegerField(default=0, verbose_name='已退还普通积分')),
                ('refund_cultural_points', models.PositiveIntegerField(default=0, verbose_name='已退还文化积分')),
                ('order_status', models.SmallIntegerField(choices=[(1, 'To ship'), (2, 'To receive'), (3, 'Completed'), (4, 'Closed')], default=1, verbose_name='订单状态')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myapp_order',
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='订单ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('phone', models.CharField(max_length=255, verbose_name='手机号')),
                ('province', models.CharField(max_length=255, verbose_name='省')),
                ('province_code', models.CharField(max_length=255, verbose_name='省 code')),
                ('city', models.CharField(max_length=255, verbose_name='市')),
                ('city_code', models.CharField(max_length=255, verbose_name='市 code')),
                ('district', models.CharField(max_length=255, verbose_name='区')),
                ('district_code', models.CharField(max_length=255, verbose_name='区 code')),
                ('detail', models.CharField(max_length=500, verbose_name='详细地址')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
            ],
            options={
                'db_table': 'myapp_order_address',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='订单ID')),
                ('goods_id', models.IntegerField(verbose_name='商品ID')),
                ('goods_image_url', models.CharField(max_length=255, verbose_name='商品图片url')),
                ('goods_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('goods_sku_id', models.IntegerField(verbose_name='商品规格ID')),
                ('goods_sku_name', models.CharField(max_length=255, verbose_name='商品规格名称')),
                ('goods_sku_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品规格价格')),
                ('goods_sku_point_num', models.PositiveIntegerField(default=0, verbose_name='商品规格积分数量')),
                ('buy_num', models.PositiveIntegerField(default=1, verbose_name='购买数量')),
                ('freight_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单商品运费金额，0元包邮')),
                ('normal_order_allocated_data', models.JSONField(verbose_name='普通商城订单商品分配数据（优惠券金额、积分数、积分金额、最后计算出来的总金额）')),
                ('points_order_allocated_data', models.JSONField(verbose_name='积分商城订单商品分配数据（使用的普通积分，文化积分）')),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (2, '申请退款中'), (3, '已退款')], default=1, verbose_name='状态')),
                ('is_comment', models.PositiveSmallIntegerField(default=0, verbose_name='是否已评价')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myapp_order_goods',
            },
        ),
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='订单ID')),
                ('order_goods_id', models.IntegerField(default=0, verbose_name='订单商品ID')),
                ('refund_type', models.SmallIntegerField(choices=[(1, 'Only refund'), (2, 'Return and refund')], verbose_name='退款类型')),
                ('refund_no', models.CharField(max_length=100, unique=True, verbose_name='退款单号')),
                ('apply_desc', models.CharField(max_length=1000, verbose_name='用户申请原因(说明)')),
                ('apply_image_urls', models.JSONField(verbose_name='用户上传的图片')),
                ('audit_status', models.SmallIntegerField(choices=[(1, 'Pending audit'), (2, 'Accepted'), (3, 'Rejected')], default=1, verbose_name='审核状态')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('is_user_send', models.PositiveSmallIntegerField(default=0, verbose_name='用户是否发货')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='用户发货时间')),
                ('express_name', models.CharField(default='', max_length=255, verbose_name='用户发货快递公司名称')),
                ('express_no', models.CharField(default='', max_length=255, verbose_name='用户发货快递单号')),
                ('is_receipt', models.PositiveSmallIntegerField(default=0, verbose_name='平台收货状态')),
                ('receipt_time', models.DateTimeField(blank=True, null=True, verbose_name='平台收货时间')),
                ('refund_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际退款金额')),
                ('refund_coupon', models.PositiveSmallIntegerField(default=0, verbose_name='本次退款是否退还优惠券')),
                ('refund_normal_points', models.PositiveIntegerField(default=0, verbose_name='退还普通积分数量')),
                ('refund_cultural_points', models.PositiveIntegerField(default=0, verbose_name='退还文化积分数量')),
                ('status', models.SmallIntegerField(choices=[(1, 'In progress'), (2, 'Rejected'), (3, 'Completed'), (4, 'Cancelled')], default=1, verbose_name='售后单状态')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myapp_order_refund',
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255, verbose_name='年画图片URL')),
                ('bg_mp3_url', models.CharField(default='', max_length=255, verbose_name='背景MP3音乐URL')),
                ('name', models.CharField(max_length=255, verbose_name='年画名称')),
                ('style_id', models.IntegerField(default=0, verbose_name='风格ID')),
                ('theme_id', models.IntegerField(default=0, verbose_name='题材ID')),
                ('dynasty_id', models.IntegerField(default=0, verbose_name='年代ID')),
                ('author_id', models.IntegerField(default=0, verbose_name='作者ID')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('is_delete', models.PositiveSmallIntegerField(default=0, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaintingAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作者姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_painting_author',
            },
        ),
        migrations.CreateModel(
            name='PaintingCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('festival_name', models.CharField(max_length=100, verbose_name='节日名称')),
                ('description', models.TextField(default='', verbose_name='节日描述')),
                ('painting_id', models.IntegerField(default=0, verbose_name='年画ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_painting_calendar',
            },
        ),
        migrations.CreateModel(
            name='PaintingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_id', models.IntegerField(verbose_name='年画ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_painting_comment',
            },
        ),
        migrations.CreateModel(
            name='PaintingDynasty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='年代名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_painting_dynasty',
            },
        ),
        migrations.CreateModel(
            name='PaintingStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='风格名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_painting_style',
            },
        ),
        migrations.CreateModel(
            name='PaintingTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='题材名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_painting_theme',
            },
        ),
        migrations.CreateModel(
            name='PointsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_fixed_points', models.PositiveIntegerField(default=0, verbose_name='每笔订单赠送积分')),
                ('normal_points_max_num', models.PositiveIntegerField(default=200, verbose_name='普通商城订单最多可使用普通积分数')),
                ('normal_points_per_yuan', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='普通积分抵扣金额(1积分抵多少金额)单位：元')),
            ],
            options={
                'db_table': 'myapp_points_config',
            },
        ),
        migrations.CreateModel(
            name='PointsGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name='分类ID')),
                ('image_urls', models.JSONField(verbose_name='图片url列表')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('detail_url', models.CharField(max_length=255, verbose_name='详情图片url')),
                ('freight_type', models.SmallIntegerField(choices=[(1, '包邮'), (2, '固定邮费'), (3, '运费模板')], verbose_name='运费类型')),
                ('freight_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费金额，0元包邮')),
                ('freight_temp_id', models.IntegerField(default=0, verbose_name='运费模板ID')),
                ('is_delete', models.PositiveSmallIntegerField(default=0, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myapp_points_goods',
            },
        ),
        migrations.CreateModel(
            name='PointsGoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_points_goods_category',
            },
        ),
        migrations.CreateModel(
            name='PointsGoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(verbose_name='商品ID')),
                ('star_num', models.PositiveSmallIntegerField(default=5, verbose_name='评分')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'myapp_points_goods_comment',
            },
        ),
        migrations.CreateModel(
            name='PointsGoodsSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(verbose_name='商品ID')),
                ('sku_name', models.CharField(max_length=255, verbose_name='SKU名称')),
                ('point_num', models.PositiveIntegerField(default=0, verbose_name='积分数量')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myapp_points_goods_sku',
            },
        ),
        migrations.CreateModel(
            name='PointsTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.SmallIntegerField(choices=[(1, '浏览年画'), (2, '收藏年画'), (3, '评论年画')], verbose_name='任务类型')),
                ('painting_id', models.IntegerField(default=0, verbose_name='年画ID')),
                ('daily_limit', models.PositiveIntegerField(default=0, verbose_name='每日次数限制')),
                ('point_reward', models.PositiveIntegerField(verbose_name='单次积分奖励')),
                ('is_delete', models.PositiveSmallIntegerField(default=0, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'myapp_points_task',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name='分类ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.CharField(max_length=1000, verbose_name='内容')),
                ('image_urls', models.JSONField(verbose_name='图片URL列表')),
                ('tags', models.JSONField(verbose_name='标签列表')),
                ('type', models.PositiveSmallIntegerField(choices=[(10, '普通帖子'), (20, '我的年画故事')], default=0, verbose_name='类型')),
                ('painting_id', models.IntegerField(default=0, verbose_name='年画ID')),
                ('painting_name', models.CharField(default='', max_length=255, verbose_name='年画名称')),
                ('painting_image_url', models.CharField(default='', max_length=255, verbose_name='年画图片URL')),
                ('video_url', models.CharField(default='', max_length=255, verbose_name='视频URL')),
                ('video_cover_url', models.CharField(default='', max_length=255, verbose_name='视频封面图片URL')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('is_delete', models.PositiveSmallIntegerField(default=0, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_posts_category',
            },
        ),
        migrations.CreateModel(
            name='PostsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_id', models.IntegerField(verbose_name='帖子ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_posts_comment',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(verbose_name='分组ID')),
                ('cn_name', models.CharField(max_length=255, verbose_name='标签名称')),
                ('en_name', models.CharField(max_length=255, verbose_name='标签名称（英文）')),
            ],
            options={
                'db_table': 'myapp_tag',
            },
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_name', models.CharField(max_length=255, verbose_name='标签名称')),
                ('en_name', models.CharField(max_length=255, verbose_name='标签名称（英文）')),
            ],
            options={
                'db_table': 'myapp_tag_group',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.CharField(max_length=32)),
                ('avatar_url', models.CharField(default='', max_length=255)),
                ('avatar_file_id', models.IntegerField()),
                ('nickname', models.CharField(default='', max_length=255)),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('birthday', models.CharField(default='', max_length=255, verbose_name='出生日期')),
                ('profession', models.CharField(default='', max_length=255, verbose_name='职业')),
                ('normal_points', models.PositiveIntegerField(default=0, verbose_name='普通积分')),
                ('cultural_points', models.PositiveIntegerField(default=0, verbose_name='文化积分')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('is_delete', models.PositiveSmallIntegerField(default=0, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('phone', models.CharField(max_length=255, verbose_name='手机号')),
                ('province', models.CharField(max_length=255, verbose_name='省')),
                ('province_code', models.CharField(max_length=255, verbose_name='省 code')),
                ('city', models.CharField(max_length=255, verbose_name='市')),
                ('city_code', models.CharField(max_length=255, verbose_name='市 code')),
                ('district', models.CharField(max_length=255, verbose_name='区')),
                ('district_code', models.CharField(max_length=255, verbose_name='区 code')),
                ('detail', models.CharField(max_length=500, verbose_name='详细地址')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_user_address',
            },
        ),
        migrations.CreateModel(
            name='UserAIImageEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, verbose_name='任务ID')),
                ('prompt', models.CharField(max_length=500, verbose_name='提示词')),
                ('status', models.CharField(max_length=50, verbose_name='生成状态')),
                ('original_url', models.CharField(max_length=255, verbose_name='原始图片URL')),
                ('image_url', models.CharField(max_length=255, verbose_name='图片URL')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_user_ai_imageedit',
            },
        ),
        migrations.CreateModel(
            name='UserAIMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='角色')),
                ('image_url', models.CharField(default='', max_length=255, verbose_name='图片URL')),
                ('text', models.TextField(verbose_name='内容')),
                ('session_id', models.CharField(max_length=255, verbose_name='会话ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_user_ai_message',
            },
        ),
        migrations.CreateModel(
            name='UserAISession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True, verbose_name='会话ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_user_ai_session',
            },
        ),
        migrations.CreateModel(
            name='UserAIText2Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, verbose_name='任务ID')),
                ('prompt', models.CharField(max_length=500, verbose_name='提示词')),
                ('status', models.CharField(max_length=50, verbose_name='生成状态')),
                ('image_url', models.CharField(max_length=255, verbose_name='图片URL')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_user_ai_text2image',
            },
        ),
        migrations.CreateModel(
            name='UserPointsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.PositiveSmallIntegerField(choices=[(10, 'Browse painting'), (20, 'Favorite painting'), (30, 'Comment painting'), (40, 'Use points for order'), (50, 'Use points for order'), (60, 'Gives points'), (70, 'Refund points')], default=0, verbose_name='场景')),
                ('point_type', models.PositiveSmallIntegerField(choices=[(10, '普通积分'), (20, '文化积分')], default=0, verbose_name='积分类型')),
                ('point_num', models.PositiveIntegerField(default=0, verbose_name='积分数量')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_user_points_log',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_group_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'myapp_user_tag',
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_type', models.SmallIntegerField(choices=[(1, 'Love'), (2, 'Wealth'), (3, 'Study'), (4, 'Health'), (5, 'Family'), (6, 'Career')], default=0, verbose_name='类型')),
                ('painting_id', models.IntegerField(default=0, verbose_name='年画ID')),
                ('content', models.CharField(max_length=255, verbose_name='许愿内容')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_wish',
            },
        ),
        migrations.CreateModel(
            name='UserView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_user_view',
                'unique_together': {('painting_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='UserPointsTaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0, verbose_name='任务ID')),
                ('task_type', models.PositiveSmallIntegerField(choices=[(1, '浏览年画'), (2, '收藏年画'), (3, '评论年画')], verbose_name='任务类型')),
                ('progress_date', models.DateField(verbose_name='进度日期')),
                ('today_count', models.PositiveIntegerField(default=0, verbose_name='今日已完成次数')),
                ('last_complete_time', models.DateTimeField(blank=True, null=True, verbose_name='最后完成时间')),
                ('painting_ids', models.JSONField(verbose_name='年画ID列表')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_user_points_task_progress',
                'unique_together': {('user_id', 'task_id', 'progress_date')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_user_favorite',
                'unique_together': {('painting_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.IntegerField(verbose_name='优惠券ID')),
                ('coupon_name', models.CharField(max_length=255, verbose_name='优惠券名称')),
                ('reduce_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='减免金额')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低消费金额')),
                ('expire_day', models.PositiveIntegerField(default=0, verbose_name='领取后有效期天数')),
                ('start_time', models.DateTimeField(verbose_name='有效期开始时间')),
                ('end_time', models.DateTimeField(verbose_name='有效期结束时间')),
                ('is_use', models.PositiveSmallIntegerField(default=0, verbose_name='是否使用')),
                ('use_time', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_user_coupon',
                'unique_together': {('user_id', 'coupon_id')},
            },
        ),
        migrations.CreateModel(
            name='PostsThumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_id', models.IntegerField(verbose_name='帖子ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_posts_thumb',
                'unique_together': {('posts_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='PaintingStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_id', models.IntegerField(verbose_name='年画ID')),
                ('star_count', models.PositiveSmallIntegerField(default=5, verbose_name='评分')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_painting_star',
                'unique_together': {('painting_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='GoodsCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(verbose_name='商品ID')),
                ('goods_sku_id', models.IntegerField(verbose_name='商品SKU ID')),
                ('buy_num', models.PositiveIntegerField(default=1, verbose_name='购买数量')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
            ],
            options={
                'db_table': 'myapp_goods_cart',
                'unique_together': {('goods_id', 'goods_sku_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='FreightTempRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255, verbose_name='区域名称')),
                ('is_default', models.PositiveSmallIntegerField(default=0, verbose_name='是否为默认全国规则')),
                ('province_code', models.TextField(blank=True, verbose_name='省编码，多个用;分隔')),
                ('city_code', models.TextField(blank=True, verbose_name='市编码，多个用;分隔')),
                ('first', models.PositiveIntegerField(default=0, verbose_name='首件')),
                ('first_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='首件运费')),
                ('continue_num', models.PositiveIntegerField(default=0, verbose_name='续件')),
                ('continue_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='续件运费')),
                ('freight_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_temp_regions', to='myapp.freighttemp', verbose_name='所属运费模板')),
            ],
            options={
                'db_table': 'myapp_freight_temp_region',
            },
        ),
    ]
