# Generated by Django 4.1.13 on 2025-07-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('article_content', models.TextField(default='', verbose_name='节日描述')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_banner',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_file_id',
            field=models.IntegerField(default=0),
        ),
    ]
