adapter_name_or_path: saves/Qwen3-4B-Instruct-2507/lora/train_2025-10-01-12-33-10
cutoff_len: 2048
dataset_dir: data
ddp_timeout: 180000000
do_predict: true
eval_dataset: nianhua_recommendation_val
finetuning_type: lora
flash_attn: auto
max_new_tokens: 512
max_samples: 100000
model_name_or_path: /root/autodl-tmp/qwen3-4B-Instruct
output_dir: saves/Qwen3-4B-Instruct-2507/lora/eval_2025-10-01-12-33-10-4B-ori
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bnb
report_to: none
stage: sft
temperature: 0.01
template: qwen3_nothink
top_p: 0.7
trust_remote_code: true
