"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#-1l))#6j0*g#ups8!ok7+!2ysuo_^dzbsd!p$zjjv2&nhrhap'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '10.0.2.2',
    '127.0.0.1',
    'localhost'
]


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp.apps.MyappConfig'
]

MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middlewares.language.LanguageMiddleware',
    'middlewares.exception.ExceptionMiddleware',
    'middlewares.video_stream.VideoStreamMiddleware',
    'myapp.middlewares.auth_token.AuthTokenMiddleware'
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = []

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
        'PORT': 3306 ,
        'NAME': '202602',
        'USER': '202602',
        'PASSWORD': '202602',
        'OPTIONS': {
            # 'autocommit': True,
            # 'init_command': 'SET default_storage_engine=InnoDB',
            # 'charset': 'utf8mb4',
            'isolation_level': "read committed"
        }
    }
}

# Cache
# https://docs.djangoproject.com/en/4.1/ref/settings/#cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# from django.utils.translation import gettext_lazy as _
LANGUAGES = (
    ('en-us', 'English'),
    ('zh-cn', '中文简体'),
    # ('en-us', _('English')),
    # ('zh-hans', _('Simplified Chinese')),
)
LOCALE_PATHS = (os.path.join(BASE_DIR, 'locale'),)
LANGUAGE_CODE = 'zh-cn'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


# 上传文件路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload/')
MEDIA_URL = '/upload/'

# 敏感词文件路径
SENSITIVE_WORDS_PATH = os.path.join(BASE_DIR, 'sensitive_words.txt')

# RAG知识库路径
RAG_KNOWLEDGE_BASE_PATH = os.path.join(BASE_DIR, 'knowledge_base')
# RAG知识库向量数据库存储路径
RAG_PERSIST_DIRECTORY = os.path.join(BASE_DIR, 'chroma_db')
# 阿里云百炼大模型KEY密钥
DASHSCOPE_API_KEY = 'sk-b36889b51cda4d469af8d7cb4a4da4dd'

# 全国快递物流查询-快递查询接口 Appcode
ALI_WULIU_APPCODE = 'e956169dc34f4287a6bcfbfee30e5897'


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django.db.backends': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     },
# }
